/* eslint-disable space-before-function-paren */

const schema = require('../hyperschema')
const runtime = require('hyperconf/runtime')

const productionEncoding = schema.getEncoding('@gear/config')
const production = decode(
  productionEncoding,
  runtime.b4a.from('AQH9CQYJaG9sZXB1bmNoAwI0cWl5c2Q5eDNjd2s0N3diMWtocmJpdzFpZThnajl1dHRudDNtd2NncjlvYnRoYjk2a3h4bzQ0ZXNjNGE5Z284cmNhZDQza2tndHJyNHV5cXNzdW8xdzlwMW96eXkzYjE0anpxNzdmaWp5Co0EYmFyZUpnaXQrcGVhcjovLzAuODQyLnV4ampoeXp5aWR1c204NHlib2M1YnF0YzhudXcxNW9zeGltcTdxd2pwenV0enEzZXU1NG8vYmFyZQE7U21hbGwgYW5kIG1vZHVsYXIgSmF2YVNjcmlwdCBydW50aW1lIGZvciBkZXNrdG9wIGFuZCBtb2JpbGWZCWh5cGVyYmVhbU5naXQrcGVhcjovLzAuMjIuYTFlOXA1NHQ0b3RqcW1wNzhxczFoNHVmcTE1cWI1NThhZjk4YmQ3c2M2eXFycG9ndWhzeS9oeXBlcmJlYW0BPkEgMS0xIGVuZC10by1lbmQgZW5jcnlwdGVkIGludGVybmV0IHBpcGUgcG93ZXJlZCBieSBIeXBlcnN3YXJthghoeXBlcmJlZU5naXQrcGVhcjovLzAuNTI2LnpoaHBicGU5aTQ1OGE0bWVycTlmZjV0bTRzN3NnOGJmcnJzaTQzdDY0emh1a283empiYnkvaHlwZXJiZWUBLEFuIGFwcGVuZC1vbmx5IEItdHJlZSBydW5uaW5nIG9uIGEgSHlwZXJjb3JlkAloeXBlcmNvcmVQZ2l0K3BlYXI6Ly8wLjMzMDcuZWhpamVpNW1najNqNWRlNjdnZXplejlwenIzeXViZDgxMTZ6amZvbmZpanhxeXl3d3dyby9oeXBlcmNvcmUBM0h5cGVyY29yZSBpcyBhIHNlY3VyZSwgZGlzdHJpYnV0ZWQgYXBwZW5kLW9ubHkgbG9nLnYIaHlwZXJkaHRPZ2l0K3BlYXI6Ly8wLjEwNDgudDd0bmNpMThoNHd3bndjcDU3aDV5OWd5NmV0MTQzMzM0YzF3bWNoOW5vZnhldDMzdHFkeS9oeXBlcmRodAEbVGhlIERIVCBwb3dlcmluZyBIeXBlcnN3YXJtlwpoeXBlcmRyaXZlUGdpdCtwZWFyOi8vMC44NjIueGFkeTl6d2VxcHQ5dG94MTNtaXg5NXp0eWZyYm1lcHlmd2czamp3cmRyaWJ0dzRvNHU2eS9oeXBlcmRyaXZlATlIeXBlcmRyaXZlIGlzIGEgc2VjdXJlLCByZWFsIHRpbWUgZGlzdHJpYnV0ZWQgZmlsZSBzeXN0ZW2vCmh5cGVyc2hlbGxPZ2l0K3BlYXI6Ly8wLjM5Lnd1N2p4dXFxemFkbnN1Y2dkZDVpd2hibXJmNzFlcGl0eTR0NTlpNjFwMWU1a25oamZodG8vaHlwZXJzaGVsbAFSU3Bhd24gc2hlbGxzIGFueXdoZXJlLiBGdWxseSBwZWVyLXRvLXBlZXIsIGF1dGhlbnRpY2F0ZWQsIGFuZCBlbmQgdG8gZW5kIGVuY3J5cHRlZJIKaHlwZXJzd2FybVBnaXQrcGVhcjovLzAuMzQwLmE1NmJjaG5neXdzdThvZ2lkdDQ2ajNkcG00bWhib3NqcWpkZnpvNGlkNXR4ejN1ZmpienkvaHlwZXJzd2FybQE0QSBkaXN0cmlidXRlZCBuZXR3b3JraW5nIHN0YWNrIGZvciBjb25uZWN0aW5nIHBlZXJzLnoEcGVhcktnaXQrcGVhcjovLzAuMjUxMy56cjg1aDhiNWExOXl5ajZtY2MzMXRxNGFhZnQ1NjdwMzRoZzl6dHluYno5dWJmdWk1aWpvL3BlYXIBJ1BlZXItdG8tUGVlciAoUDJQKSBJbnN0YWxsICYgRGVwbG95IENMSYQNc29kaXVtLW5hdGl2ZVNnaXQrcGVhcjovLzAuNzA3LjNzeWRnM2N4bzNwbTN5azFoNnQ3YzdpdDg0MzY4aXh3ZW85bTRjajE0NXFhM2M3OXVtaXkvc29kaXVtLW5hdGl2ZQEgTG93IGxldmVsIGJpbmRpbmdzIGZvciBsaWJzb2RpdW0=', 'base64')
)

const developmentEncoding = null
const development = null

module.exports = {
  production,
  development,
  productionEncoding,
  developmentEncoding
}

function decode(enc, buf) {
  return enc.decode({ start: 0, end: buf.byteLength, buffer: buf })
}
