// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

const { c } = require('hyperschema/runtime')

const VERSION = 1

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @gear/repo
const encoding0 = {
  preencode(state, m) {
    c.string.preencode(state, m.name)
    c.string.preencode(state, m.url)
    state.end++ // max flag is 1 so always one byte

    if (m.description) c.string.preencode(state, m.description)
  },
  encode(state, m) {
    const flags = m.description ? 1 : 0

    c.string.encode(state, m.name)
    c.string.encode(state, m.url)
    c.uint.encode(state, flags)

    if (m.description) c.string.encode(state, m.description)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      name: r0,
      url: r1,
      description: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @gear/source.blindPeers
const encoding1_1 = c.array(c.string)
// @gear/source.repos
const encoding1_2 = c.array(c.frame(encoding0))

// @gear/source
const encoding1 = {
  preencode(state, m) {
    c.string.preencode(state, m.name)
    state.end++ // max flag is 2 so always one byte

    if (m.blindPeers) encoding1_1.preencode(state, m.blindPeers)
    if (m.repos) encoding1_2.preencode(state, m.repos)
  },
  encode(state, m) {
    const flags = (m.blindPeers ? 1 : 0) | (m.repos ? 2 : 0)

    c.string.encode(state, m.name)
    c.uint.encode(state, flags)

    if (m.blindPeers) encoding1_1.encode(state, m.blindPeers)
    if (m.repos) encoding1_2.encode(state, m.repos)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      name: r0,
      blindPeers: (flags & 1) !== 0 ? encoding1_1.decode(state) : null,
      repos: (flags & 2) !== 0 ? encoding1_2.decode(state) : null
    }
  }
}

// @gear/config.sources
const encoding2_0 = c.array(c.frame(encoding1))

// @gear/config
const encoding2 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.sources) encoding2_0.preencode(state, m.sources)
  },
  encode(state, m) {
    const flags = m.sources ? 1 : 0

    c.uint.encode(state, flags)

    if (m.sources) encoding2_0.encode(state, m.sources)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      sources: (flags & 1) !== 0 ? encoding2_0.decode(state) : null
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@gear/repo':
      return encoding0
    case '@gear/source':
      return encoding1
    case '@gear/config':
      return encoding2
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = {
  resolveStruct,
  getStruct,
  getEnum,
  getEncoding,
  encode,
  decode,
  setVersion,
  version
}
